import Link from 'next/link'
import { ArrowRight, Check, Globe2, Handshake, Sparkles, Users, ShieldCheck } from 'lucide-react'
import { FadeUp, ScaleIn } from '@/components/Motion'
import { ServiceIcon, Arrow } from '@/components/Icons'
import { BeforeAfter } from '@/components/BeforeAfter'
import { services } from '@/lib/site'

export default function Home(){return <main>
<section className="relative overflow-hidden pt-36 sm:pt-44"><div className="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_78%_12%,rgba(8,148,240,.18),transparent_28%),radial-gradient(circle_at_10%_65%,rgba(99,196,0,.08),transparent_30%)]"/><div className="absolute inset-0 -z-10 opacity-70 grid-fade"/><div className="container-nw pb-20 lg:pb-28"><div className="grid items-end gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><FadeUp><div className="eyebrow text-[#0894F0]">Central North Carolina • Built to grow</div></FadeUp><FadeUp delay={.06}><h1 className="display mt-5 max-w-5xl text-5xl font-bold leading-[.96] sm:text-6xl lg:text-8xl">Good work.<br/><span className="text-[#0894F0]">Built bigger.</span></h1></FadeUp><FadeUp delay={.12}><p className="mt-7 max-w-xl text-lg leading-8 text-[#5A6678] sm:text-xl">Neighborly Work handles the outdoor and property jobs people need done right — while building a pathway for young people to learn the business behind the work.</p></FadeUp><FadeUp delay={.18}><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="btn-primary">Get a Quote <ArrowRight size={18} className="ml-2"/></Link><Link href="/join" className="btn-secondary">Work or Franchise With Us</Link></div></FadeUp></div><ScaleIn delay={.12} className="relative"><div className="rounded-[2.6rem] border border-white/70 bg-white/70 p-4 shadow-soft backdrop-blur"><div className="relative min-h-[440px] overflow-hidden rounded-[2rem] bg-[#0B1220]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(8,148,240,.5),transparent_33%),linear-gradient(150deg,#152130,#0b1220)]"/><div className="absolute right-6 top-6 rounded-full bg-white/10 px-4 py-2 text-xs font-semibold text-white backdrop-blur">Doing the work. Building the next thing.</div><div className="absolute bottom-0 left-0 right-0 p-7 text-white"><div className="eyebrow text-white/45">The Neighborly Work model</div><div className="mt-3 max-w-lg text-3xl font-semibold leading-tight sm:text-4xl">Serve customers well. Teach the business. Help people build.</div><div className="mt-7 grid grid-cols-3 gap-3">{[['01','Service'],['02','Opportunity'],['03','Growth']].map(([n,t])=><div key={n} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="text-xs text-white/45">{n}</div><div className="mt-2 text-sm font-semibold">{t}</div></div>)}</div></div></div></div></ScaleIn></div></div></div></section>

<section className="section-pad border-y border-slate-100 bg-white"><div className="container-nw"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><FadeUp><div><div className="eyebrow text-[#0894F0]">What we do</div><h2 className="display mt-4 text-4xl font-bold sm:text-5xl">The work is simple.<br/>The standard is not.</h2></div></FadeUp><div className="grid gap-4 sm:grid-cols-2">{services.map((s,i)=><FadeUp key={s.title} delay={i*.05}><Link href="/services" className="service-card group block"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eef8ff] text-[#0894F0]"><ServiceIcon icon={s.icon}/></div><Arrow/></div><div className="eyebrow mt-7 text-slate-400">{s.eyebrow}</div><h3 className="mt-2 text-xl font-bold">{s.title}</h3><p className="mt-2 text-sm leading-6 text-[#5A6678]">{s.blurb}</p></Link></FadeUp>)}</div></div></div></section>

<section className="section-pad bg-[#0B1220] text-white"><div className="container-nw"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><FadeUp><div><div className="eyebrow text-[#63C400]">Before / after</div><h2 className="display mt-4 text-4xl font-bold sm:text-5xl">Small details make a property feel handled.</h2><p className="mt-5 max-w-md text-white/60 leading-7">A premium service brand should show its work. This is a placeholder comparison component ready for your real project photography.</p></div></FadeUp><FadeUp delay={.08}><BeforeAfter before="A job that needs attention" after="A property that feels ready" label="Placeholder • swap with real photos"/></FadeUp></div></div></section>

<section id="story" className="section-pad"><div className="container-nw"><div className="grid gap-12 lg:grid-cols-[1fr_.9fr]"><FadeUp><div className="eyebrow text-[#0894F0]">Our story</div><h2 className="display mt-4 text-4xl font-bold sm:text-5xl">It started with trash cans.</h2><div className="prose-lite mt-6 max-w-2xl"><p>Neighborly Work was founded today by two teenagers who started with a simple service: cleaning trash cans. From there, the goal is to build a serious operation that can serve entire neighborhoods and take on the outdoor and property work customers actually need.</p><p>That origin matters. The company is designed around the idea that real work teaches real business — how to sell, serve, communicate, solve problems, and take responsibility for a result.</p></div><div className="mt-8"><Link href="/about" className="btn-secondary">Read Our Story <ArrowRight size={18} className="ml-2"/></Link></div></FadeUp><ScaleIn className="rounded-[2.5rem] bg-[#eef8ff] p-7"><div className="h-full rounded-[2rem] border border-[#cceeff] bg-white p-7"><div className="eyebrow text-[#0894F0]">From the first job to the long game</div><div className="mt-8 space-y-6">{[['01','Start small','Do a useful job well.'],['02','Learn the business','Build confidence through real reps.'],['03','Build something','Use the playbook, network, and skills to grow.']].map(([n,t,d])=><div key={n} className="flex gap-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#0B1220] text-xs font-bold text-white">{n}</div><div><div className="font-bold">{t}</div><div className="mt-1 text-sm text-[#5A6678]">{d}</div></div></div>)}</div></div></ScaleIn></div></div></section>

<section id="mission" className="section-pad bg-[#f6fbfe]"><div className="container-nw"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><FadeUp><div><div className="eyebrow text-[#0894F0]">Impact & mission</div><h2 className="display mt-4 text-4xl font-bold sm:text-5xl">Make the work good. Make the opportunity real.</h2></div></FadeUp><div className="grid gap-4 sm:grid-cols-2">{[['Service','Customers get excellent work and straightforward communication.'],['Materials','People building a local operation get the practical resources to start.'],['Marketing','Learn how to find customers, tell the story, and grow demand.'],['Networking','Build relationships with other operators and people who know the work.']].map(([t,d],i)=><FadeUp key={t} delay={i*.06}><div className="rounded-[2rem] border border-slate-200 bg-white p-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#0B1220] text-white">{i===0?<ShieldCheck size={21}/>:i===1?<Sparkles size={21}/>:i===2?<Globe2 size={21}/>:<Handshake size={21}/>}</div><h3 className="mt-6 text-xl font-bold">{t}</h3><p className="mt-2 leading-7 text-[#5A6678]">{d}</p></div></FadeUp>)}</div></div><FadeUp delay={.12}><div className="mt-10 rounded-[2.5rem] bg-[#0B1220] p-7 sm:p-10"><div className="max-w-3xl text-2xl font-semibold leading-tight text-white sm:text-4xl">“Do the work. Learn the business. Build something that is yours.”</div><div className="mt-4 text-sm text-white/50">Core brand idea — not a customer testimonial.</div></div></FadeUp></div></section>

<section id="join" className="section-pad"><div className="container-nw"><div className="rounded-[2.8rem] bg-[linear-gradient(135deg,#0894F0,#0b77bd)] p-8 text-white sm:p-12 lg:p-16"><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><FadeUp><div><div className="eyebrow text-white/60">Join the build</div><h2 className="display mt-4 text-4xl font-bold sm:text-6xl">Work with us.<br/>Or build with us.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Neighborly Work is actively building a team and a path for people who want to operate a local business with the Neighborly Work name and support behind it.</p></div></FadeUp><FadeUp delay={.08}><div className="grid gap-3"><Link href="/join#work" className="btn-secondary border-white/20 bg-white text-[#0B1220]">Apply to Work <ArrowRight size={18} className="ml-2"/></Link><Link href="/join#franchise" className="btn-secondary border-white/20 bg-white/10 text-white hover:bg-white/15">Franchise With Us <ArrowRight size={18} className="ml-2"/></Link></div></FadeUp></div></div></div></section>

<section id="reviews" className="section-pad bg-white"><div className="container-nw"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><FadeUp><div><div className="eyebrow text-[#0894F0]">Reviews</div><h2 className="display mt-4 text-4xl font-bold sm:text-5xl">Let the work speak.</h2><p className="mt-4 max-w-xl text-[#5A6678]">This section is intentionally ready for verified customer feedback. Do not publish invented testimonials.</p></div></FadeUp><Link href="/contact#review" className="btn-secondary">Leave a Review</Link></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['Verified feedback','Customer testimonial placeholder','Replace with real review + first name/last initial.'],['Recent project','Customer testimonial placeholder','Add service type + date when available.'],['Neighborhood partner','Customer testimonial placeholder','Only use after receiving permission.']].map(([a,b,c],i)=><FadeUp key={a} delay={i*.06}><div className="rounded-[2rem] border border-dashed border-slate-300 p-7"><div className="eyebrow text-slate-400">{a}</div><div className="mt-5 text-lg font-semibold text-slate-500">“{b}”</div><div className="mt-4 text-sm leading-6 text-[#5A6678]">{c}</div></div></FadeUp>)}</div></div></section>

<section className="section-pad border-t border-slate-100 bg-[#f7fafc]"><div className="container-nw"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><FadeUp><div><div className="eyebrow text-[#0894F0]">Ready when you are</div><h2 className="display mt-4 text-4xl font-bold sm:text-5xl">Tell us what needs done.</h2><p className="mt-5 max-w-md leading-7 text-[#5A6678]">Get in touch for service, partnerships, employment, or franchise interest.</p></div></FadeUp><FadeUp delay={.08}><div className="rounded-[2.3rem] border border-slate-200 bg-white p-7 shadow-soft sm:p-9"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><div className="eyebrow text-slate-400">Service area</div><div className="mt-2 font-bold">Central North Carolina</div></div><div className="rounded-2xl bg-slate-50 p-5"><div className="eyebrow text-slate-400">Email</div><div className="mt-2 font-bold">hello@neighborlywork.com</div></div></div><Link href="/contact" className="btn-primary mt-4 w-full">Get in Contact <ArrowRight size={18} className="ml-2"/></Link><div className="mt-4 text-center text-xs text-slate-400">Phone currently shown as a placeholder in this prototype.</div></div></FadeUp></div></div></section>
</main>}
