import Link from 'next/link'
import Image from 'next/image'
export function Footer(){return <footer className="border-t border-slate-200 bg-[#0b1220] text-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1.3fr_.7fr_.7fr_.9fr]"><div><Image src="/brand/neighborly-work-logo-horizontal-on-dark.svg" alt="Neighborly Work" width={220} height={42} className="h-9 w-auto"/><p className="mt-5 max-w-md text-sm leading-7 text-white/65">Hands-on outdoor and property services in Central North Carolina — with a bigger mission to help people build something of their own.</p><div className="mt-5 flex gap-3" aria-label="Social media">
  <a className="social-pill" href="https://www.facebook.com/profile.php?id=61594666230232" target="_blank" rel="noopener noreferrer" aria-label="Neighborly Work on Facebook" title="Facebook">
    <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M13.5 21v-8.2h2.76l.41-3.2H13.5V7.56c0-.93.26-1.56 1.6-1.56h1.7V3.14C16.5 3.05 15.48 3 14.3 3c-2.48 0-4.18 1.52-4.18 4.31V9.6H7.3v3.2h2.82V21h3.38Z"/></svg>
  </a>
  <a className="social-pill" href="https://www.instagram.com/neighborly_work/" target="_blank" rel="noopener noreferrer" aria-label="Neighborly Work on Instagram" title="Instagram">
    <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>
  </a>
  <a className="social-pill" href="https://www.linkedin.com/company/neighborly-work/" target="_blank" rel="noopener noreferrer" aria-label="Neighborly Work on LinkedIn" title="LinkedIn">
    <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M5.2 3.5a1.9 1.9 0 1 0 0 3.8 1.9 1.9 0 0 0 0-3.8ZM3.6 9h3.2v11H3.6V9Zm5.2 0h3.1v1.5h.05c.43-.82 1.48-1.68 3.05-1.68 3.27 0 3.88 2.15 3.88 4.95V20h-3.25v-5.52c0-1.32-.03-3.02-1.84-3.02-1.84 0-2.12 1.44-2.12 2.92V20H8.8V9Z"/></svg>
  </a>
</div></div><div><div className="footer-title">Explore</div>{[['Home','/'],['Services','/services'],['Our Story','/about'],['Impact & Mission','/#mission']].map(([x,y])=><Link key={x} href={y} className="footer-link">{x}</Link>)}</div><div><div className="footer-title">Join</div>{[['Work with us','/join'],['Franchise','/join#franchise'],['Request Service','/contact']].map(([x,y])=><Link key={x} href={y} className="footer-link">{x}</Link>)}</div><div><div className="footer-title">Service area</div><p className="text-sm leading-7 text-white/65">Central North Carolina</p><div className="mt-5 space-y-2 text-sm text-white/65"><a className="block transition hover:text-white" href="mailto:service.neighborly.work@gmail.com">service.neighborly.work@gmail.com</a><a className="block transition hover:text-white" href="tel:9195796519">919-579-6519</a></div></div></div><div className="mt-14 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Neighborly Work. All rights reserved.</span><span>Built around honest work, excellent service, and opportunity.</span></div></div></footer>}